### ISSUE TITLE
Module unmaintained: Transfer ownership?

### ISSUE THREAD

**Issue by chillu** [alexei/silverstripe-unidecode#5]
@hafriedlander @alexei @JT5D @olvlvl @dedurus @amal @dmnapolitano @romaincointepas @kukawski

You have all expressed interest in this module over time by creating issues, pull requests, starring or forking on github, or committing code.

SilverStripe Ltd. can no longer commit to maintaining this module, and we suspect there aren't many active users out there. We are planning to remove it from our github repository, and wanted to give you a chance to express interest in taking over ownership. This primarily means providing it with a new home under your own github account. Users should also have a reasonable chance on getting a response from you if they have trouble with it.

If you are interested in taking on this module, please let us know in the next two weeks.

Background: https://groups.google.com/forum/#!topic/silverstripe-dev/vgQZpUnxrI4

**Comment by alexei** [comment]
It would be a shame for it to disappear completely as it's useful. I have a library that depends on this module so I don't intend on removing my fork. 

Albeit I kind of moved away from PHP, I can take the ownership if you'd like or if no one else is interested, and add a license (BSD-3) and composer support, do some cleanup e.g. remove svn-commit.tmp file, fix bugs where appropriate etc.

**Comment by chillu** [comment]
@alexei Awesome, thanks for offering to take ownership! We'll wait two weeks to give others a chance to speak up. 

@hafriedlander As the author of the code, can you please add a license so we can make it a clean and unambiguous move?

**Comment by chillu** [comment]
I've added a BSD-3 license now, which was already implied by the comments in `code/Unidecode.php`. Left the exception in place for the README:

> Note that all the files named 'x??.php' in data are derived directly from the equivilent perl file, and both sets of files are distributed under the perl license,
and not the BSD license.

@alexei In order to transfer ownership, you need to remove your fork. If you have applied any commits on top of the upstream codebase, you need to reapply them. Is that possible for you?

**Comment by alexei** [comment]
There's a an open PR #2 with my changes. You could accept it before transfering the repo

**Comment by chillu** [comment]
Done!

**Comment by alexei** [comment]
Cool, I deleted my fork

**Comment by chillu** [comment]
I've given you admin access on this repo, which should enable you to initiate the transfer: https://github.com/silverstripe-labs/silverstripe-unidecode/settings

**Comment by alexei** [comment]
Done

**Comment by alexei** [comment]
So I guess we can close this issue.

Thank you!

**Comment by alexei** [comment]
Hopefully you won't mind I rename the project to php-unidecode or something and also update the README & LICENSE files to reflect the changes.

**Comment by chillu** [comment]
All good, thank you Alexei!
